//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.08 at 08:12:16 AM IST 
//


package com.example.webservice.schema;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nextRoute" type="{http://www.example.org/GraphService}GraphPoint" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nextRoute"
})
@XmlRootElement(name = "GetRouteResponse")
public class GetRouteResponse {

    @XmlElement(required = true)
    protected List<GraphPoint> nextRoute;

    /**
     * Gets the value of the nextRoute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nextRoute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNextRoute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GraphPoint }
     * 
     * 
     */
    public List<GraphPoint> getNextRoute() {
        if (nextRoute == null) {
            nextRoute = new ArrayList<GraphPoint>();
        }
        return this.nextRoute;
    }

	public void setNextRoute(LinkedList<GraphPoint> list) {
		 this.nextRoute = list;
		
	}

}
