//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.08 at 08:12:16 AM IST 
//


package com.example.webservice.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sendRouteRequest" type="{http://www.example.org/GraphService}GraphPoint"/>
 *         &lt;element name="destRouteRequest" type="{http://www.example.org/GraphService}GraphPoint"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendRouteRequest",
    "destRouteRequest"
})
@XmlRootElement(name = "SendRouteRequest")
public class SendRouteRequest {

    @XmlElement(required = true)
    protected GraphPoint sendRouteRequest;
    @XmlElement(required = true)
    protected GraphPoint destRouteRequest;

    /**
     * Gets the value of the sendRouteRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GraphPoint }
     *     
     */
    public GraphPoint getSendRouteRequest() {
        return sendRouteRequest;
    }

    /**
     * Sets the value of the sendRouteRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GraphPoint }
     *     
     */
    public void setSendRouteRequest(GraphPoint value) {
        this.sendRouteRequest = value;
    }

    /**
     * Gets the value of the destRouteRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GraphPoint }
     *     
     */
    public GraphPoint getDestRouteRequest() {
        return destRouteRequest;
    }

    /**
     * Sets the value of the destRouteRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GraphPoint }
     *     
     */
    public void setDestRouteRequest(GraphPoint value) {
        this.destRouteRequest = value;
    }

}
